repository_type: pipeline
lint:
  files_exist:
    - conf/igenomes.config
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
  nextflow_config:
    - config_defaults:
        - params.dfast_config
nf_core_version: "2.14.1"
